### ISSUE TITLE
Use the correct environment variables for RUM agent config

### ISSUE THREAD

**Issue by jahtalab** [elastic/opbeans-python#16]
In order to use the same variables across agents we should use the following variables to config the RUM agent:

- `ELASTIC_APM_JS_BASE_SERVER_URL` - Elastic APM Server URL for the
  client app (default: `http://localhost:3000`)
- `ELASTIC_APM_JS_BASE_SERVICE_NAME` - Elastic APM App Name for the
  client app (defaults to `name` from [opbeans-frontend package.json
  file](https://github.com/elastic/opbeans-frontend/blob/master/package.json)
- `ELASTIC_APM_JS_BASE_SERVICE_VERSION` - Elastic APM App Name for the
  client app (defaults to `version` from [opbeans-frontend package.json
  file](https://github.com/elastic/opbeans-frontend/blob/master/package.json)

[opbeans-node issue](https://github.com/elastic/opbeans-node/issues/38)

**Comment by gingerwizard** [comment]
I think this is also preventing source maps from working as the version doesn't seem to be set - the apm server thus receives 

```{"level":"error","timestamp":"2018-10-04T15:26:31.290Z","logger":"stacktrace","caller":"model/stacktrace_frame.go:219","message":"Sourcemap Key Error for Service Name: 'opbeans-react', Service Version: '' and Path: 'https://opbeans-python.dev.ingress.eden.elstc.co/products/6'"}```
